name: 'Parse Unity Logs'

description: 'Runs a script that parses errors and warnings from a Unity log file'

inputs:

  log-path:
    description: "Path to the log file"
    required: true
    type: string

outputs:
  errors:
    description: "Parsed errors from the log file"

runs:
  using: "composite"
  steps:

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
      shell: bash

    - name: Parse unity Log
      run: |
        python parser.py
      env:
        LOG_PATH: ${{ inputs.log-path }}
      shell: bash
    - name: Generate Error Annotations
      run: |
        text="This is an Error"
        echo "::error file=app.js,line=10,col=15::$text"
      shell: bash
    - name: Generate Warning Annotations
      run: |
        text="This is a Warning"
        echo "::warning file=app.js,line=10,col=15::$text"
      shell: bash
        