name: Parse unity logs
run-name: ${{ inputs.log-path }}
on:
  workflow_dispatch:
    inputs:
      log-path:
        description: 'Path to the log file'
        required: true
        type: choice
        options:
          - 'logs/sample-project-failure.log'
          - 'logs/sample-project-success.log'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello

    steps:
      - uses: actions/checkout@v4

      - id: foo
        uses: bdorin/hello-world-composite-action@main
        with:
          who-to-greet: 'Mona the Octocat'

      - run: |
          import os
          print(f"random-number {os.environ['RANDOM_NUMBER']}")
        shell: python
        env:
          RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}
