name: Parse unity logs
run-name: ${{ inputs.log-path }}
on:
  workflow_dispatch:
    inputs:
      log-path:
        description: 'Path to the log file'
        required: true
        type: choice
        options:
          - 'logs/sample-project-failure.log'
          - 'logs/sample-project-success.log'
      eliminate-duplicates:
        description: 'Eliminate duplicate errors and warnings'
        required: false
        type: boolean
        default: false

jobs:
  Parse-Unity-Logs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Parse logs
        uses: bdorin/hello-world-composite-action/.github/custom-actions@main
        with:
          log-path: ${{ inputs.log-path }}
      - name: Debug ELIMINATE_DUPLICATES
        run: echo "ELIMINATE_DUPLICATES = $ELIMINATE_DUPLICATES"
        shell: bash
        env:
          ELIMINATE_DUPLICATES: ${{ inputs.eliminate-duplicates }}